### PR TITLE
Check all hypotheses in CI

### PR DESCRIPTION
**Pull request by actyp**
Update the learning `-roundLimit` and the number of hypotheses checked in `ci.yml`, in order to check the correctness of all the intermediate hypotheses.

### CODE REVIEW

**Comment by kostis** [comment]
My view is that we should _not_ have CI tests that take long to run., because this slows down development.
In particular, the time to complete the EDHOC-RS Server test is _way too long_.  At least that change should be reverted.

**Comment by actyp** [comment]
I share the same view. I would like also to experiment in this PR with the timing parameters of the arguments, in case they can reduce the delay.

**Comment by actyp** [comment]
I think now that the duration of the tests is acceptable.

**Review by kostis — APPROVED** [review]
Nicely done!

**Pull request merged**
